server:
  port: 8091

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.244.62.128:3306/video?characterEncoding=utf8&useSSL=false
    username: video
    password: video


video:
  options:
    initTask:
      threadCount: 10